server:
  restart: always
  build: ./server
  expose:
    - "5000"
  # ports:
  #   - "5000:5000"
  command: /usr/local/bin/gunicorn -w 4 --bind :5000 api:app

proxy:
  restart: always
  build: ./proxy/
  # expose:
  #   - "8080"
  ports:
    - "8080:8080"
  volumes_from:
    - server
  links:
    - server:server
